# Site settings
title: The Stanley Fair
header-img: img/fairgrounds2014.jpg
header-img-credit: Emily Dextraze
email: leahbelyea@gmail.com
description: "The longest continuously running agricultural fair in New Brunswick"
baseurl: ""
url: "http://stanleyfair.com"
facebook_username: groups/134846959887178/
excerpt_separator: <!--end-excerpt-->

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
paginate_path: news-events/page:num
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","npm-debug.log", "Gemfile", "Gemfile.lock"]

# Gems
gems: [jekyll-paginate]


# Dropbox
# baseurl: "https://dl.dropboxusercontent.com/u/112632688"
# permalink: none
